### ISSUE TITLE
Roadmap v2

### ISSUE THREAD

**Issue by stijnvanhulle** [kubb-project/kubb#556]
> [!NOTE]\
> PR: https://github.com/kubb-project/kubb/pull/549
Installation: https://beta.kubb.dev//installation
Docs: https://beta.kubb.dev/

### Why
<details><summary>Summary</summary>
<p>

[Discord](https://discord.com/channels/1117538769235615835/1117538769877356767/1166772115714887802)

Hi all, I created a roadmap on Github for v2: https://github.com/kubb-project/kubb/issues/556.
Why?

I have been working on some changes related to the architecture of Kubb which will make it faster and easier but it's taking more time to get it ready. So v2 will not be a breaking change but with the changes that will be added it can cause weird behaviours(don't want to do this with a major bump). 

v2 will also include a rewrite of how  `react-query` is getting generated so that all issues related to using `useQuery` and `useMutation` will be resolved(v4 and v5).

All of this will be added to the  `alpha` tag on NPM and with the playground you can also select the `alpha` build: https://www.kubb.dev/playground.
</p>
</details> 

### Features/fixes

- [x] https://github.com/kubb-project/kubb/issues/542 
- [x] https://github.com/kubb-project/kubb/issues/621
- [x] Use of `PluginKey` instead of the plugin.name
```typescript
type PluginKey = [pluginName: string, identifier: number]
```
- [x] 📔 Multiple(array of) `KubbConfig` when calling `defineConfig`
- [x] sort imports/exports based on `type` => import type will be last
- [x] PluginManager.write without the queue 
- [x] 📔 Better support for namespace `Kubb` in TypeScript(with help of `declare const`)
- [x] Fast build times with a change in the `printer` in `@kubb/parser` 
- [x] 📔 Name for logging
- [x] Use of logger instead of throwing Errors(PluginError, ...)
- [x] 📔 https://github.com/kubb-project/kubb/issues/527
- [x] https://github.com/kubb-project/kubb/issues/528
- [x] https://github.com/kubb-project/kubb/pull/550
- [x] https://github.com/kubb-project/kubb/issues/530
- [x] https://github.com/kubb-project/kubb/issues/530#issuecomment-1784205674
- [x] https://github.com/kubb-project/kubb/issues/513
- [x] https://github.com/kubb-project/kubb/issues/582
- [x] Better resolveName and resolvePath system
- [x] Test cases for all PlugingManagers hooks
- [x] https://github.com/kubb-project/kubb/issues/648
- [x] Better support for OpenAPI v3.1
- [x] [Add `useSuspenseQuery` for @tanstack/query](https://github.com/kubb-project/kubb/pull/595)
- [x] Templates for schema creations
- [ ] Use of `queryOptions` for @tanstack/query v5
- [ ] Refactor of `FunctionParams`
- [x] Disable barrel files https://github.com/kubb-project/kubb/issues/552
- [x] tsconfigPaths esbuild plugin instead of alias for vitest
- [x] tsup update
- [x] disable barrel exports
- [x] Mutate(tanstack and SWR) with props/params for the URL

### Explore

- [x] RTK Query https://redux-toolkit.js.org/rtk-query/overview Cancelled see https://redux-toolkit.js.org/rtk-query/usage/code-generation
- [ ] Http-wizard https://github.com/flodlc/http-wizard
- [x] Better changelog generation with 
- https://github.com/intuit/auto
- https://github.com/mikepenz/release-changelog-builder-action 
- https://github.com/mikepenz/release-changelog-builder-action/issues/986
- https://github.com/colinhacks/zod/blob/master/.github/workflows/release.yml
- https://github.com/TanStack/table/blob/main/scripts/publish.ts
- https://github.com/orhun/git-cliff
- [ ] https://github.com/tinylibs/tinypool

* 📔 = docs added

**Comment by stijnvanhulle** [comment]
@la55u I added your issue for the mutation to the list(https://github.com/kubb-project/kubb/issues/530#issuecomment-1784205674). I will have a look later this week to fix it :)

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
How about if deleting the deprecated `client` option is also added in 2.0?

**Comment by la55u** [comment]
React-query is further complicating things.. In v5 there is a separate hook now for queries if you want to make use of Suspense: `useSuspenseQuery`. AFAIK `useQuery` and `useSuspenseQuery` are for different use-cases: you have to use the first one if you explicitly _don't_ want to use Suspense and the second one if you do, there is no option anymore to disable it on a per-query basis. Since most IRL projects will have edge cases where it's desired to be able to disable suspense behavior I suppose both `useQuery` and `useSuspenseQuery` custom hooks should be generated with kubb? Please someone correct me if I'm wrong I'm just getting started with react-query v5.

**Comment by kalagin** [comment]
Is RTK Query implementation planned?

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
When do you expect the v2 release?

**Comment by stijnvanhulle** [comment]
@b6pzeusbc54tvhw5jgpyw8pwz2x6gs Probably in a couple of weeks, it will depend on how much time I will have in the coming weeks :)

**Comment by stijnvanhulle** [comment]
@kalagin I would suggest using https://redux-toolkit.js.org/rtk-query/usage/code-generation with that it's maintained by the creators of Redux.
